name: label-check
on:
  pull_request:
    types:
      - labeled
jobs:
  functional-test:
    if: github.event.label.name == 'ok-to-test'
    runs-on: [ubuntu-latest]
    steps:
      - name: setup
        run: |
          sudo apt update
          sudo apt install python-pip
          pip install --user awscli
          curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl $HOME/.local/bin
          curl -sSL -o $HOME/.local/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x $HOME/.local/bin/jq
          export PATH=$PATH:$HOME/.local/bin
          jq --version
          kubectl
          aws --version

      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: docker-build
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: keikoproj/instance-manager-test
          tag_with_sha: true

      - name: test

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NODE_SUBNETS: ${{ secrets.NODE_SUBNETS }}
          NODE_ROLE: ${{ secrets.NODE_ROLE }}
        run: |
          HEAD=$(git rev-parse --short HEAD)
          export SECURITY_GROUPS=$(aws cloudformation describe-stacks --stack-name nightly-eks-node-security-group --query "Stacks[0].Outputs[?OutputKey=='SecurityGroup'].OutputValue" --output text)
          export AMI_ID=ami-076c743acc3ec4159
          export AWS_REGION=us-west-2
          export KEYPAIR_NAME=instancemgr-bdd

          aws eks update-kubeconfig --name instancemgr-eks-nightly
          make install
          kubectl set image -n instance-manager deployment/instance-manager instance-manager=keikoproj/instance-manager-test:sha-$HEAD
          make bdd