name: functional-test

on:
  issue_comment:
    types: [created]

jobs:
  functional-test:
    name: functional-test
    if: github.event.issue.pull_request && github.event.issue_comment.body == '/test'
    runs-on: ubuntu-latest
    steps:

      - name: setup
        run: |
          sudo apt update
          sudo apt install python-pip
          pip install --user awscli
          curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl $HOME/.local/bin
          curl -sSL -o $HOME/.local/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x $HOME/.local/bin/jq
          export PATH=$PATH:$HOME/.local/bin
          jq --version
          kubectl
          aws --version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: docker-build-push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: keikoproj/instance-manager-test
          tags: ${{ github.event.pull_request.head.sha }}

      - name: test
        id: test
        env:
          AWS_REGION: us-west-2
          AWS_DEFAULT_REGION: us-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NODE_SUBNETS: ${{ secrets.NODE_SUBNETS }}
          NODE_ROLE: ${{ secrets.NODE_ROLE }}
          KEYPAIR_NAME: ${{ secrets.KEYPAIR_NAME }}
          AMI_ID: ${{ secrets.AMI_ID }}
          SECURITY_GROUPS: ${{ secrets.SECURITY_GROUPS }}
          EKS_CLUSTER: ${{ secrets.CLUSTER_NAME }}
        run: |
          HEAD=$(git rev-parse --short HEAD)
          aws eks update-kubeconfig --name $EKS_CLUSTER
          make install
          kubectl set image -n instance-manager deployment/instance-manager instance-manager=keikoproj/instance-manager-test:${{ github.event.pull_request.head.sha }}
          echo "##[set-output name=result;]$(make bdd)"

      - name: comment PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ${{ steps.test.outputs.result }}
          check_for_duplicate_msg: true